# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
imagePullSecrets: image-pull-secret
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}

securityContext: {}

deployment:
  name: external-todo

service:
  name: external-todo
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: "alb"
  host: flbetances-todo.cjoga.cloud
  paths:
    - path: /
      pathType: Prefix
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: flbetances-todo
    alb.ingress.kubernetes.io/subnets: <subnet-ids>
    alb.ingress.kubernetes.io/security-groups: <security-group-id>
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: <certificate-arn>
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
  tls: []
app:
  port: 3000
  replicaCount: 1
  revisionHistoryLimit: 1
  image:
    name: "cjoga/flbetances-test:latest"
    pullPolicy: IfNotPresent
    pullSecret: image-pull-secret
    rollback: "cjoga/flbetances-test:latest"
resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
build: app
