apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  name: "{{  .Chart.Name }}-ingress"
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{  .Values.ingress.host }}
    http:
      paths:
        {{- range .Values.ingress.paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: "{{ default $.Chart.Name $.Values.service.name }}"
              port:
                number: {{ $.Values.app.port }}
        {{- end }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
